//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Obligatorio_RedFlix.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clima
    {
        public int IdClima { get; set; }
        public string Ciudad { get; set; }
        public Nullable<decimal> Temperatura { get; set; }
        public string EstadoClima { get; set; }
        public Nullable<int> Humedad { get; set; }
        public System.DateTime FechaConsulta { get; set; }
    }
}
