//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Obligatorio_RedFlix.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListaContenido
    {
        public int IdListaContenido { get; set; }
        public int IdLista { get; set; }
        public Nullable<int> IdPelicula { get; set; }
        public Nullable<int> IdSerie { get; set; }
        public System.DateTime FechaAgregado { get; set; }
    
        public virtual ListasPersonalizada ListasPersonalizada { get; set; }
        public virtual Pelicula Pelicula { get; set; }
        public virtual Series Series { get; set; }
    }
}
