//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Obligatorio_RedFlix.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pago
    {
        public int IdPago { get; set; }
        public int IdCompra { get; set; }
        public int IdMetodoPago { get; set; }
        public decimal Monto { get; set; }
        public System.DateTime FechaPago { get; set; }
        public string Estado { get; set; }
    
        public virtual Compra Compra { get; set; }
        public virtual MetodosPago MetodosPago { get; set; }
    }
}
