//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Obligatorio_RedFlix.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrecioContenido
    {
        public int IdPrecio { get; set; }
        public int TmdbId { get; set; }
        public string Titulo { get; set; }
        public string TipoContenido { get; set; }
        public decimal PrecioCompra { get; set; }
        public decimal PrecioAlquier { get; set; }
        public int DiasAlquiler { get; set; }
        public bool Activo { get; set; }
    }
}
