//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Obligatorio_RedFlix.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PromocionesClima
    {
        public int IdPromocion { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public string CondicionClima { get; set; }
        public Nullable<decimal> TemperaturaMax { get; set; }
        public decimal PorcentajeDesc { get; set; }
        public Nullable<int> IdGenero { get; set; }
        public bool Activa { get; set; }
    
        public virtual Genero Genero { get; set; }
    }
}
