//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Obligatorio_RedFlix.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recomendacione
    {
        public int IdRecomendacion { get; set; }
        public int IdUsuario { get; set; }
        public Nullable<int> IdPelicula { get; set; }
        public Nullable<int> IdSerie { get; set; }
        public string Motivo { get; set; }
        public System.DateTime FechaRecomendacion { get; set; }
    
        public virtual Pelicula Pelicula { get; set; }
        public virtual Series Series { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
