//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Obligatorio_RedFlix.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RedFlixDBEntities : DbContext
    {
        public RedFlixDBEntities()
            : base("name=RedFlixDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Calificacione> Calificaciones { get; set; }
        public virtual DbSet<CarritoItem> CarritoItems { get; set; }
        public virtual DbSet<Carrito> Carritos { get; set; }
        public virtual DbSet<Clima> Climas { get; set; }
        public virtual DbSet<Compra> Compras { get; set; }
        public virtual DbSet<Cotizacione> Cotizaciones { get; set; }
        public virtual DbSet<DetalleCompra> DetalleCompras { get; set; }
        public virtual DbSet<Favorito> Favoritos { get; set; }
        public virtual DbSet<Genero> Generos { get; set; }
        public virtual DbSet<HistorialBusqueda> HistorialBusquedas { get; set; }
        public virtual DbSet<HistorialReproduccion> HistorialReproduccions { get; set; }
        public virtual DbSet<ListaContenido> ListaContenidoes { get; set; }
        public virtual DbSet<ListasPersonalizada> ListasPersonalizadas { get; set; }
        public virtual DbSet<MetodosPago> MetodosPagoes { get; set; }
        public virtual DbSet<Pago> Pagos { get; set; }
        public virtual DbSet<Pelicula> Peliculas { get; set; }
        public virtual DbSet<Permiso> Permisos { get; set; }
        public virtual DbSet<Recomendacione> Recomendaciones { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<RolesPermiso> RolesPermisos { get; set; }
        public virtual DbSet<Series> Series { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }
    }
}
